language: cpp
sudo: required

os:
  - linux
  #- osx

compiler:
  - clang
  - gcc

cache: ccache

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
      compiler: clang
  exclude:
    - os: osx
compiler: gcc
